# Generated by Django 4.2.11 on 2024-07-31 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(default='', max_length=255)),
                ('val_percent_permitido_autofinanciamento', models.FloatField(default=0)),
                ('val_permitido_autofinanciamento', models.FloatField(default=0)),
                ('total_autofin_financeiro', models.FloatField(default=0)),
                ('total_autofin_estimavel_bens', models.FloatField(default=0)),
                ('total_autofin_estimavel_veiculos', models.FloatField(default=0)),
                ('total_autofin_totalizado', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
                ('tipo_cargo', models.PositiveSmallIntegerField(choices=[(1, 'VEREADOR'), (2, 'PREFEITO'), (3, 'VICE-PREFEITO')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20, unique=True)),
                ('estado', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Comerc_bens_realiz_eventos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('com_bens_FEFC', models.FloatField(default=0)),
                ('com_bens_FP', models.FloatField(default=0)),
                ('com_bens_OR', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Grupo_despesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('descricao', models.CharField(default='', max_length=255)),
                ('limite', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='limites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Partido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigla', models.CharField(max_length=20, unique=True)),
                ('nome', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Rec_outras_receitas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rec_ori_nao_identificada', models.FloatField(default=0)),
                ('comerc_bens_realiz_eventos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financas.comerc_bens_realiz_eventos')),
            ],
        ),
        migrations.CreateModel(
            name='Rec_outros_candidatos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FEFC', models.FloatField(default=0)),
                ('fundo_partidario', models.FloatField(default=0)),
                ('outros', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Rec_partido_politico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FEFC', models.FloatField(default=0)),
                ('outros', models.FloatField(default=0)),
                ('doacoes_internet', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Rend_aplic_financeiras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FEFC', models.FloatField(default=0)),
                ('fundo_partidario', models.FloatField(default=0)),
                ('outros', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Teto_gasto_cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField(default=0)),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financas.cargo')),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financas.cidade')),
            ],
        ),
        migrations.CreateModel(
            name='Receita_financeiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rec_proprios', models.FloatField(default=0)),
                ('rec_pessoas_fisicas', models.FloatField(default=0)),
                ('aquisicao_doacao_bens_moveis_imoveis', models.FloatField(default=0)),
                ('rec_financiamento_coletivo', models.FloatField(default=0)),
                ('devolucao_receitas', models.FloatField(default=0)),
                ('devolucao_rec_orig_nao_identificadoas', models.FloatField(default=0)),
                ('total', models.FloatField(default=0)),
                ('rec_outras_receitas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financas.rec_outras_receitas')),
                ('rec_outros_candidatos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financas.rec_outros_candidatos')),
                ('rec_partido_politico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financas.rec_partido_politico')),
            ],
        ),
        migrations.CreateModel(
            name='Receita_estimavel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rec_proprios', models.FloatField(default=0)),
                ('rec_pessoas_fisicas', models.FloatField(default=0)),
                ('aquisicao_doacao_bens_moveis_imoveis', models.FloatField(default=0)),
                ('rec_financiamento_coletivo', models.FloatField(default=0)),
                ('devolucao_receitas', models.FloatField(default=0)),
                ('devolucao_rec_orig_nao_identificadoas', models.FloatField(default=0)),
                ('total', models.FloatField(default=0)),
                ('rec_outras_receitas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financas.rec_outras_receitas')),
                ('rec_outros_candidatos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financas.rec_outros_candidatos')),
                ('rec_partido_politico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financas.rec_partido_politico')),
            ],
        ),
        migrations.CreateModel(
            name='Receita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.FloatField(default=0)),
                ('rec_estimavel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financas.receita_estimavel', unique=True)),
                ('rec_financeira', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financas.receita_financeiro', unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='rec_outras_receitas',
            name='rend_aplic_financeiras',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financas.rend_aplic_financeiras'),
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=255, unique=True)),
                ('nome', models.CharField(max_length=255)),
                ('profissão', models.CharField(max_length=255, null=True)),
                ('dnascimento', models.DateField(null=True)),
                ('endereco', models.CharField(max_length=255, null=True)),
                ('cep', models.CharField(max_length=255, null=True)),
                ('fone', models.CharField(max_length=255, null=True)),
                ('email', models.CharField(max_length=255, null=True)),
                ('status', models.IntegerField(null=True)),
                ('rendimento_bruto_irpf2024', models.FloatField(default=0, null=True)),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financas.cidade')),
            ],
        ),
        migrations.CreateModel(
            name='Item_despesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('descricao', models.CharField(default='', max_length=255)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financas.grupo_despesa')),
            ],
        ),
        migrations.CreateModel(
            name='Doador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('val_limite_doacao_financeira', models.FloatField(default=0)),
                ('val_limite_doacao_estimavel', models.FloatField(default=0)),
                ('val_limite_total', models.FloatField(default=0)),
                ('total_doacao_financeira', models.FloatField(default=0)),
                ('total_doacao_estimavel', models.FloatField(default=0)),
                ('total_doacao_totalizado', models.FloatField(default=0)),
                ('situacao', models.CharField(default='Normal', max_length=255)),
                ('candidato', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='financas.candidato')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financas.pessoa', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Doacoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(null=True)),
                ('valor', models.FloatField(default=0)),
                ('tipo_doacao', models.PositiveSmallIntegerField(choices=[(0, 'FINANCEIRO'), (1, 'CESSÃO DE VEICULOS '), (3, 'CESSÃO DE BENS ')], default=0)),
                ('doador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='financas.doador')),
            ],
        ),
        migrations.CreateModel(
            name='Despesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField(default=0)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financas.item_despesa')),
            ],
        ),
        migrations.AddField(
            model_name='candidato',
            name='cargo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='financas.cargo'),
        ),
        migrations.AddField(
            model_name='candidato',
            name='despesa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='financas.despesa'),
        ),
        migrations.AddField(
            model_name='candidato',
            name='partido',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='financas.partido'),
        ),
        migrations.AddField(
            model_name='candidato',
            name='pessoa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financas.pessoa', unique=True),
        ),
        migrations.AddField(
            model_name='candidato',
            name='receita',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='financas.receita'),
        ),
    ]
