# Generated by Django 4.2.11 on 2024-07-30 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('profissão', models.CharField(max_length=255, null=True)),
                ('dnascimento', models.DateField(null=True)),
                ('endereco', models.CharField(max_length=255, null=True)),
                ('cep', models.CharField(max_length=255, null=True)),
                ('cidade', models.CharField(max_length=255, null=True)),
                ('fone', models.CharField(max_length=255, null=True)),
                ('email', models.CharField(max_length=255, null=True)),
                ('status', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_cargo', models.PositiveSmallIntegerField(choices=[(1, 'VEREADOR'), (2, 'PREFEITO')], default=1)),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financas.pessoa')),
            ],
        ),
    ]
