# Generated by Django 4.2.11 on 2024-07-30 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('descricao', models.CharField(default='', max_length=255)),
                ('tipo_cargo', models.PositiveSmallIntegerField(choices=[(1, 'VEREADOR'), (2, 'PREFEITO'), (3, 'VICE-PREFEITO')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20, unique=True)),
                ('estado', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Limite_gasto_cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField(default=0)),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financas.cargo')),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financas.cidade')),
            ],
        ),
        migrations.DeleteModel(
            name='Chapa',
        ),
        migrations.RemoveField(
            model_name='candidato',
            name='tipo_cargo',
        ),
        migrations.AddField(
            model_name='candidato',
            name='cargo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='financas.cargo'),
            preserve_default=False,
        ),
    ]
