# Generated by Django 4.2.11 on 2024-07-30 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0002_cargo_cidade_limite_gasto_cargo_delete_chapa_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pessoa',
            old_name='name',
            new_name='nome',
        ),
    ]
