# Generated by Django 4.2.11 on 2024-07-30 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0004_receita'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigla', models.CharField(max_length=20, unique=True)),
                ('descricao', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Rec_outras_receitas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('com_bens_FEFC', models.FloatField(default=0)),
                ('com_bens_FP', models.FloatField(default=0)),
                ('com_bens_OR', models.FloatField(default=0)),
                ('FEFC', models.FloatField(default=0)),
                ('fundo_partidario', models.FloatField(default=0)),
                ('outros', models.FloatField(default=0)),
                ('rec_ori_nao_identificada', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Rec_outros_candidatos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FEFC', models.FloatField(default=0)),
                ('fundo_partidario', models.FloatField(default=0)),
                ('outros', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Rec_partido_politico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FEFC', models.FloatField(default=0)),
                ('outros', models.FloatField(default=0)),
                ('doacoes_internet', models.FloatField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='receita',
            name='candidato',
        ),
        migrations.AddField(
            model_name='candidato',
            name='receita',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='financas.receita', unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='candidato',
            name='pessoa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financas.pessoa', unique=True),
        ),
        migrations.CreateModel(
            name='Receita_estimavel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rec_proprios', models.FloatField(default=0)),
                ('rec_pessoas_fisicas', models.FloatField(default=0)),
                ('aquisicao_doacao_bens_moveis_imoveis', models.FloatField(default=0)),
                ('rec_financiamento_coletivo', models.FloatField(default=0)),
                ('devolucao_receitas', models.FloatField(default=0)),
                ('devolucao_rec_orig_nao_identificadoas', models.FloatField(default=0)),
                ('total', models.FloatField(default=0)),
                ('rec_outras_receitas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financas.rec_outras_receitas')),
                ('rec_outros_candidatos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financas.rec_outros_candidatos')),
                ('rec_partido_politico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financas.rec_partido_politico')),
            ],
        ),
        migrations.AddField(
            model_name='candidato',
            name='partido',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='financas.partido'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='receita',
            name='rec_estimavel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='financas.receita_estimavel', unique=True),
            preserve_default=False,
        ),
    ]
