# Generated by Django 4.2.11 on 2024-07-30 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0005_partido_rec_outras_receitas_rec_outros_candidatos_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receita_financeiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rec_proprios', models.FloatField(default=0)),
                ('rec_pessoas_fisicas', models.FloatField(default=0)),
                ('aquisicao_doacao_bens_moveis_imoveis', models.FloatField(default=0)),
                ('rec_financiamento_coletivo', models.FloatField(default=0)),
                ('devolucao_receitas', models.FloatField(default=0)),
                ('devolucao_rec_orig_nao_identificadoas', models.FloatField(default=0)),
                ('total', models.FloatField(default=0)),
                ('rec_outras_receitas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financas.rec_outras_receitas')),
                ('rec_outros_candidatos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financas.rec_outros_candidatos')),
                ('rec_partido_politico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financas.rec_partido_politico')),
            ],
        ),
        migrations.AddField(
            model_name='receita',
            name='rec_financeira',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='financas.receita_financeiro', unique=True),
            preserve_default=False,
        ),
    ]
