# Generated by Django 4.2.11 on 2024-07-30 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0006_receita_financeiro_receita_rec_financeira'),
    ]

    operations = [
        migrations.CreateModel(
            name='grupo_despesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('descricao', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='receita',
            name='total',
            field=models.FloatField(default=0),
        ),
        migrations.CreateModel(
            name='item_despesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('descricao', models.CharField(default='', max_length=255)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financas.grupo_despesa')),
            ],
        ),
        migrations.CreateModel(
            name='Despesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField(default=0)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financas.item_despesa')),
            ],
        ),
        migrations.AddField(
            model_name='candidato',
            name='despesa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='financas.despesa', unique=True),
            preserve_default=False,
        ),
    ]
