# Generated by Django 4.2.11 on 2024-07-30 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0007_grupo_despesa_receita_total_item_despesa_despesa_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='limites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='grupo_despesa',
            name='limite',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='rendimento_bruto_irpf2024',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.CreateModel(
            name='doacoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_doacao', models.PositiveSmallIntegerField(choices=[(0, 'FINANCEIRA'), (1, 'ESTIMAVEL/CESSAO')], default=0)),
                ('valor', models.FloatField(default=0)),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financas.pessoa', unique=True)),
            ],
        ),
    ]
