# Generated by Django 4.2.11 on 2024-07-30 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0008_limites_grupo_despesa_limite_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comerc_bens_realiz_eventos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('com_bens_FEFC', models.FloatField(default=0)),
                ('com_bens_FP', models.FloatField(default=0)),
                ('com_bens_OR', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Rend_aplic_financeiras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FEFC', models.FloatField(default=0)),
                ('fundo_partidario', models.FloatField(default=0)),
                ('outros', models.FloatField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='rec_outras_receitas',
            name='FEFC',
        ),
        migrations.RemoveField(
            model_name='rec_outras_receitas',
            name='com_bens_FEFC',
        ),
        migrations.RemoveField(
            model_name='rec_outras_receitas',
            name='com_bens_FP',
        ),
        migrations.RemoveField(
            model_name='rec_outras_receitas',
            name='com_bens_OR',
        ),
        migrations.RemoveField(
            model_name='rec_outras_receitas',
            name='fundo_partidario',
        ),
        migrations.RemoveField(
            model_name='rec_outras_receitas',
            name='outros',
        ),
        migrations.AddField(
            model_name='rec_outras_receitas',
            name='comerc_bens_realiz_eventos',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='financas.comerc_bens_realiz_eventos'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rec_outras_receitas',
            name='rend_aplic_financeiras',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='financas.rend_aplic_financeiras'),
            preserve_default=False,
        ),
    ]
