# Generated by Django 4.2.11 on 2024-07-30 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0009_comerc_bens_realiz_eventos_rend_aplic_financeiras_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidato',
            name='despesa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financas.despesa'),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='receita',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financas.receita'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='cidade',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='financas.cidade'),
            preserve_default=False,
        ),
    ]
