# Generated by Django 4.2.11 on 2024-07-30 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0010_alter_candidato_despesa_alter_candidato_receita_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partido',
            name='descricao',
            field=models.CharField(max_length=250),
        ),
    ]
