# Generated by Django 4.2.11 on 2024-07-30 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0011_alter_partido_descricao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partido',
            old_name='descricao',
            new_name='nome',
        ),
    ]
