# Generated by Django 4.2.11 on 2024-07-30 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0012_rename_descricao_partido_nome'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cargo',
            name='codigo',
        ),
        migrations.RemoveField(
            model_name='cargo',
            name='descricao',
        ),
        migrations.AddField(
            model_name='cargo',
            name='nome',
            field=models.CharField(default=1, max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
