# Generated by Django 4.2.11 on 2024-07-30 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0013_remove_cargo_codigo_remove_cargo_descricao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidato',
            name='codigo',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='cargo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='financas.cargo'),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='despesa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='financas.despesa'),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='partido',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='financas.partido'),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='receita',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='financas.receita'),
        ),
    ]
