# Generated by Django 4.2.11 on 2024-07-30 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0014_candidato_codigo_alter_candidato_cargo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='estado',
            field=models.CharField(default=1, max_length=2),
            preserve_default=False,
        ),
    ]
