# Generated by Django 4.2.11 on 2024-07-30 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0015_pessoa_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pessoa',
            name='cidade',
        ),
    ]
