# Generated by Django 4.2.11 on 2024-07-30 23:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0016_remove_pessoa_cidade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pessoa',
            name='estado',
        ),
        migrations.AddField(
            model_name='pessoa',
            name='cidade',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='financas.cidade'),
            preserve_default=False,
        ),
    ]
