# Generated by Django 4.2.11 on 2024-07-31 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0017_remove_pessoa_estado_pessoa_cidade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doacoes',
            name='pessoa',
        ),
        migrations.AlterField(
            model_name='doacoes',
            name='tipo_doacao',
            field=models.PositiveSmallIntegerField(choices=[(0, 'FINANCEIRO'), (1, 'CESSAO')], default=0),
        ),
        migrations.CreateModel(
            name='Doador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limite_docao_financeira', models.FloatField(default=0)),
                ('total_doacao_financeira', models.FloatField(default=0)),
                ('total_doacao_cessao', models.FloatField(default=0)),
                ('total_doacao_totalizado', models.FloatField(default=0)),
                ('lst_docoes', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='financas.doacoes')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financas.pessoa', unique=True)),
            ],
        ),
    ]
