# Generated by Django 4.2.11 on 2024-07-31 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0018_remove_doacoes_pessoa_alter_doacoes_tipo_doacao_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doador',
            old_name='total_doacao_cessao',
            new_name='total_doacao_estimavel',
        ),
        migrations.AlterField(
            model_name='doacoes',
            name='tipo_doacao',
            field=models.PositiveSmallIntegerField(choices=[(0, 'FINANCEIRO'), (1, 'ESTIMAVEL')], default=0),
        ),
    ]
