# Generated by Django 4.2.11 on 2024-07-31 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0019_rename_total_doacao_cessao_doador_total_doacao_estimavel_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doador',
            old_name='lst_docoes',
            new_name='docoes',
        ),
    ]
