# Generated by Django 4.2.11 on 2024-07-31 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0020_rename_lst_docoes_doador_docoes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doador',
            old_name='limite_docao_financeira',
            new_name='val_limite_docao_financeira',
        ),
    ]
