# Generated by Django 4.2.11 on 2024-07-31 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0021_rename_limite_docao_financeira_doador_val_limite_docao_financeira'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doador',
            old_name='val_limite_docao_financeira',
            new_name='val_limite_doacao_estimavel',
        ),
        migrations.AddField(
            model_name='doador',
            name='val_limite_doacao_financeira',
            field=models.FloatField(default=0),
        ),
    ]
