# Generated by Django 4.2.11 on 2024-07-31 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0022_rename_val_limite_docao_financeira_doador_val_limite_doacao_estimavel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doador',
            name='docoes',
        ),
        migrations.AddField(
            model_name='doacoes',
            name='doador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='financas.doador'),
        ),
    ]
