# Generated by Django 4.2.11 on 2024-07-31 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0023_remove_doador_docoes_doacoes_doador'),
    ]

    operations = [
        migrations.AddField(
            model_name='doacoes',
            name='data',
            field=models.DateField(null=True),
        ),
    ]
