# Generated by Django 4.2.11 on 2024-07-31 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0024_doacoes_data'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Limite_gasto_cargo',
            new_name='Teto_gasto_cargo',
        ),
    ]
