# Generated by Django 4.2.11 on 2024-07-31 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0025_rename_limite_gasto_cargo_teto_gasto_cargo'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidato',
            name='total_autofin_estimavel_bens',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='candidato',
            name='total_autofin_estimavel_veiculos',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='candidato',
            name='total_autofin_financeiro',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='candidato',
            name='total_autofin_totalizado',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='candidato',
            name='val_permitido_autofinanciamento',
            field=models.FloatField(default=0),
        ),
    ]
