# Generated by Django 4.2.11 on 2024-07-31 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0026_candidato_total_autofin_estimavel_bens_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doacoes',
            name='tipo_doacao',
            field=models.PositiveSmallIntegerField(choices=[(0, 'FINANCEIRO'), (1, 'CESSÃO VEICULOS '), (3, 'CESSÃO BENS ')], default=0),
        ),
    ]
