# Generated by Django 4.2.11 on 2024-07-31 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0027_alter_doacoes_tipo_doacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidato',
            name='val_percent_permitido_autofinanciamento',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='doacoes',
            name='tipo_doacao',
            field=models.PositiveSmallIntegerField(choices=[(0, 'FINANCEIRO'), (1, 'CESSÃO DE VEICULOS '), (3, 'CESSÃO DE BENS ')], default=0),
        ),
    ]
