# Generated by Django 4.2.11 on 2024-07-31 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0028_candidato_val_percent_permitido_autofinanciamento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doacoes',
            name='candidato',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='financas.candidato'),
        ),
    ]
